# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# uv_nv_to_s_tif.py
# Created on: 2014-10-03 11:29:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
Horizontal_wind_input = "H:\\esm296-4f\\lab1\\raw\\uwnd.sig995.2013.nc"
Vertical_wind_input = "H:\\esm296-4f\\lab1\\raw\\vwnd.sig995.2013.nc"
v__j_ = "v_%j%"
Output_wind_speed = "H:\\esm296-4f\\lab1\\lab1.gdb\\s_001b"
u__j_ = "u_%j%"
Resampled_wind_speed = "H:\\esm296-4f\\lab1\\out\\s_001.tif"

# Process: For
arcpy.IterateCount_mb("1", "365", "30")

# Process: Make NetCDF Raster Layer (2)
arcpy.MakeNetCDFRasterLayer_md(Horizontal_wind_input, "uwnd", "lon", "lat", u__j_, "", "time 1", "BY_INDEX")

# Process: Make NetCDF Raster Layer
arcpy.MakeNetCDFRasterLayer_md(Vertical_wind_input, "vwnd", "lon", "lat", v__j_, "", "time 1", "BY_INDEX")

# Process: Wind calculator
arcpy.gp.RasterCalculator_sa("SquareRoot( Square(\"v_%j%\") + Square(\"u_%j%\") )", Output_wind_speed)

# Process: Resample
arcpy.Resample_management(Output_wind_speed, Resampled_wind_speed, "0.25 0.25", "BILINEAR")

